sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: 
    access-key-secret: 
    bucket-name: gengduc-springboot-oss
  redis:
    host: 101.42.157.148
    port: 6379
    database: 0
    password: redis
  wechat:
    appid: wx591edac9e188dad7
    secret: 8fa3ac54fafcff1649e6cf2d04c4b9cb
    mchid:
    mchSerialNo:
    privateKeyFilePath:
    apiV3Key:
    wechatPayCertFilePath:
    notifyUrl:
    refundNotifyUrl: